# Generated by Django 5.2.17 on 2026-08-07 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('plan', models.CharField(choices=[('GROWTH', 'Growth'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='GROWTH', max_length=20)),
                ('region', models.CharField(default='eu-central-1', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PLATFORM_OWNER', 'Platform owner'), ('TENANT_ADMIN', 'Tenant admin'), ('AGENT', 'Agent'), ('END_USER', 'End user')], default='END_USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('tenant__name', 'user__email'),
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='uniq_membership_user_tenant'), models.CheckConstraint(condition=models.Q(models.Q(('role', 'PLATFORM_OWNER'), ('tenant__isnull', True)), models.Q(models.Q(('role', 'PLATFORM_OWNER'), _negated=True), ('tenant__isnull', False)), _connector='OR'), name='platform_owner_has_no_tenant')],
            },
        ),
    ]
