# Generated by Django 5.2.17 on 2026-08-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_rls_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="support_email",
            field=models.EmailField(
                blank=True,
                help_text="Escalations are emailed here. Falls back to the platform default.",
                max_length=254,
            ),
        ),
    ]
