# Generated by Django 5.2.17 on 2026-08-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_tenant_support_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="assistant_instructions",
            field=models.TextField(
                blank=True,
                help_text="Workspace-specific guidance for the assistant: tools you use, local policy, house style. Cannot override grounding or escalation.",
                max_length=4000,
            ),
        ),
    ]
