# Generated by Django 5.2.17 on 2026-08-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0004_tenant_assistant_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="smtp_from_email",
            field=models.EmailField(
                blank=True,
                help_text="The From address on escalation emails. Must be one your mail server may send as.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_password_ciphertext",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="smtp_username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
