# Generated by Django 5.2.17 on 2026-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0006_alter_tenant_smtp_from_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="smtp_from_name",
            field=models.CharField(
                blank=True,
                help_text="Display name on escalation emails. Defaults to the workspace name.",
                max_length=120,
            ),
        ),
    ]
