# Generated by Django 5.2.17 on 2026-08-15 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0007_tenant_smtp_from_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField(max_length=500)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Turn off temporarily without losing the wording."
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_rules",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "position"], name="tenancy_ass_tenant__29b595_idx"
                    )
                ],
            },
        ),
    ]
