# Generated by Django 5.2.17 on 2026-08-16 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0009_assistantrule_rls_and_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The workspace's primary administrator.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
