# Generated by Django 5.2.17 on 2026-08-07 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text & Reasoning (DeepSeek)"),
                            ("VISION", "Vision & OCR (Gemini)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                ("input_per_1m", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("output_per_1m", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("per_image", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("effective_from", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("engine", "model", "-effective_from"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("engine", "model", "effective_from"), name="uniq_price_point"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text & Reasoning (DeepSeek)"),
                            ("VISION", "Vision & OCR (Gemini)"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("ciphertext", models.TextField(editable=False)),
                ("last4", models.CharField(editable=False, max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RATE_LIMITED", "Rate-limited"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(default=1)),
                (
                    "daily_quota",
                    models.PositiveIntegerField(
                        blank=True, help_text="Requests per day. Null means unmetered.", null=True
                    ),
                ),
                ("requests_today", models.PositiveIntegerField(default=0)),
                ("quota_reset_on", models.DateField(blank=True, null=True)),
                ("cooldown_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("engine", "label"),
                "indexes": [
                    models.Index(fields=["engine", "status"], name="ai_provider_engine_0e0834_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("engine", "label"), name="uniq_key_engine_label"
                    )
                ],
            },
        ),
    ]
