# Generated by Django 5.2.17 on 2026-08-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerkey",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text="Overrides the provider default. Required for a generic endpoint.",
            ),
        ),
        migrations.AddField(
            model_name="providerkey",
            name="model",
            field=models.CharField(
                blank=True, help_text="Overrides the provider default model.", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="providerkey",
            name="provider",
            field=models.CharField(
                choices=[
                    ("DEEPSEEK", "DeepSeek"),
                    ("GEMINI", "Google Gemini (native SDK)"),
                    ("OPENAI_COMPATIBLE", "OpenAI-compatible endpoint"),
                ],
                default="OPENAI_COMPATIBLE",
                help_text="Who serves the role. Swapping this never changes the engine contract.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="modelprice",
            name="engine",
            field=models.CharField(
                choices=[("TEXT", "Text & Reasoning"), ("VISION", "Vision & OCR")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="providerkey",
            name="engine",
            field=models.CharField(
                choices=[("TEXT", "Text & Reasoning"), ("VISION", "Vision & OCR")],
                db_index=True,
                help_text="The role this key fills.",
                max_length=10,
            ),
        ),
    ]
