# Generated by Django 5.2.17 on 2026-08-08 06:13

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_rls_policies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("abbreviation", models.CharField(blank=True, max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "storage_key",
                    models.CharField(help_text="Object storage key, never a URL.", max_length=512),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("DOCX", "Word"), ("MD", "Markdown")], max_length=8
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PARSING", "Parsing"),
                            ("DESCRIBING", "Describing images"),
                            ("EMBEDDING", "Embedding"),
                            ("INDEXED", "Indexed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("image_count", models.PositiveIntegerField(default=0)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="knowledge.category",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("block_index", models.PositiveIntegerField()),
                ("page", models.PositiveIntegerField(default=0)),
                ("mime_type", models.CharField(max_length=40)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("description_text", models.TextField(blank=True)),
                (
                    "describe_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DESCRIBED", "Described"),
                            ("SKIPPED", "Skipped"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("describe_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "ordering": ("document", "block_index"),
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
                ),
                ("from_image", models.BooleanField(default=False)),
                ("source_page", models.PositiveIntegerField(default=0)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("document", "ordinal"),
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uniq_category_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["tenant", "status"], name="knowledge_d_tenant__336a8e_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentasset",
            constraint=models.UniqueConstraint(
                fields=("document", "block_index"), name="uniq_asset_per_block"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["tenant", "document"], name="knowledge_d_tenant__fd69f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="chunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("document", "ordinal"), name="uniq_chunk_ordinal"
            ),
        ),
    ]
