# Generated by Django 5.2.17 on 2026-08-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_rls_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="escalation_recipient",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="message",
            name="escalation_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
