# Generated by Django 5.2.17 on 2026-08-07 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0002_rls_policies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text & Reasoning (DeepSeek)"),
                            ("VISION", "Vision & OCR (Gemini)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("chat", "Chat completion"),
                            ("classify", "Intent classification"),
                            ("describe_image", "Image description"),
                            ("embed", "Embedding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("image_count", models.PositiveSmallIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("succeeded", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"], name="metering_us_tenant__417e8a_idx"
                    )
                ],
            },
        ),
    ]
