# Generated by Django 5.2.17 on 2026-08-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering", "0002_rls_policies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageevent",
            name="engine",
            field=models.CharField(
                choices=[("TEXT", "Text & Reasoning"), ("VISION", "Vision & OCR")], max_length=10
            ),
        ),
    ]
