# Generated by Django 5.2.17 on 2026-08-14 15:50

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering", "0003_alter_usageevent_engine"),
        ("tenancy", "0003_tenant_support_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "monthly_usd",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
                ),
                (
                    "enforce",
                    models.BooleanField(
                        default=False, help_text="Refuse provider calls once the cap is reached."
                    ),
                ),
                (
                    "alert_at_percent",
                    models.PositiveSmallIntegerField(
                        default=80, help_text="Warn on the dashboard at this percentage of the cap."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant__name",),
            },
        ),
    ]
