# Generated by Django 5.2.17 on 2026-08-15 13:26

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering", "0004_tenantbudget"),
        ("tenancy", "0006_alter_tenant_smtp_from_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "per_1m_tokens",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Charged per 1,000,000 tokens, prompt and completion together.",
                        max_digits=10,
                    ),
                ),
                (
                    "per_image",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Charged per screenshot read by the vision engine.",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank applies to every workspace. Set it to override one.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_rates",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant__name", "-effective_from"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "effective_from"), name="uniq_billing_rate_point"
                    )
                ],
            },
        ),
    ]
