# Generated by Django 5.2.17 on 2026-08-15 23:31

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering", "0005_billingrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrate",
            name="per_escalation",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Charged per escalation emailed to the helpdesk.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="billingrate",
            name="per_request",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0"),
                help_text="Charged per question asked, whatever its length.",
                max_digits=10,
            ),
        ),
    ]
