# Generated by Django 5.2.17 on 2026-08-16 00:49

from django.db import migrations, models

# Existing caps are dollars and cannot be converted: the exchange rate between
# provider cost and tokens depends on price rows that were never entered, which
# is the whole reason this changed. Dropping the old column therefore leaves
# every workspace uncapped rather than guessing a number that would silently cut
# somebody off.
#
# Safe in practice: enforcement was never able to fire, so no cap is being
# relaxed - one that never worked is being replaced by one that does.


class Migration(migrations.Migration):

    dependencies = [
        ("metering", "0006_billingrate_per_escalation_billingrate_per_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantbudget",
            name="monthly_usd",
        ),
        migrations.AddField(
            model_name="tenantbudget",
            name="monthly_tokens",
            field=models.BigIntegerField(
                default=0, help_text="Prompt and completion tokens per month. Zero means no limit."
            ),
        ),
    ]
