# Generated by Django 5.2.17 on 2026-08-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_username", models.CharField(blank=True, max_length=255)),
                ("smtp_password_ciphertext", models.TextField(blank=True, editable=False)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, help_text="The From address on platform emails.", max_length=254
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True,
                        default="MateAssist",
                        help_text="Display name on platform emails.",
                        max_length=120,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "platform settings",
            },
        ),
    ]
